-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "companyName" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "companyStreet" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "companyZip" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "companyCity" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "companyCountry" TEXT DEFAULT 'DE';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "isBusinessCustomer" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "acceptedB2BTermsAt" TIMESTAMP(3);
